from enum import Enum

class BookingStatus(str, Enum):
    IDLE = "IDLE"
    COLLECTING_BOOKING_DETAILS = "COLLECTING_BOOKING_DETAILS"
    REFINING_RESULTS = "REFINING_RESULTS"
    AWAITING_HOTEL_SELECTION = "AWAITING_HOTEL_SELECTION"
    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
    AWAITING_PAYMENT = "AWAITING_PAYMENT"
    BOOKING_CONFIRMED = "BOOKING_CONFIRMED"
