from enum import Enum

class UserIntent(str, Enum):
    GREETING = "GREETING"
    START_BOOKING = "START_BOOKING"
    REFINE_PREFERENCES = "REFINE_PREFERENCES"
    SELECT_HOTEL = "SELECT_HOTEL"
    CONFIRM_BOOKING = "CONFIRM_BOOKING"
    PAYMENT = "PAYMENT"
    OTHER = "OTHER"
